eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serverUrl: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8761